<a href="https://colab.research.google.com/github/AANG-804/2021-8-PNU-AI-/blob/main/AI_%EC%95%84%EC%B9%B4%EB%8D%B0%EB%AF%B8_2021%EB%85%84_8%EC%9B%94_11%EC%9D%BC_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AI 아카데미 2021년 8월 11일 Review

## NumPy

In [1]:
import numpy as np

In [9]:
# reshape

origin_arry = np.arange(20)

reshape_arry = np.reshape(origin_arry, (20,1))
print(origin_arry)
print(origin_arry.shape)
print(reshape_arry)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [10]:
# -1을 이용하여 가변적인 shape 변경

reshape2_arry = np.reshape(origin_arry, (-1,4))
reshape3_arry = np.reshape(origin_arry, (-1,2,2))
reshape4_arry = np.reshape(origin_arry, (-1,2,5))

print(reshape2_arry)
print(reshape3_arry)
print(reshape4_arry)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [11]:
# -1은 하나만 사용할 수 있음
reshape5_arry = np.reshape(origin_arry, (-1,-1,4))
print(reshape5_arry)

ValueError: ignored

In [17]:
# 넘파이 기본연산

arry1 = np.arange(1,28).reshape(3,3,3)
arry2 = np.arange(27,0,-1).reshape(3,3,3)
print(arry1)
print(arry2)

sum_arry = arry1 + arry2
print(sum_arry)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[27 26 25]
  [24 23 22]
  [21 20 19]]

 [[18 17 16]
  [15 14 13]
  [12 11 10]]

 [[ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]]
[[[28 28 28]
  [28 28 28]
  [28 28 28]]

 [[28 28 28]
  [28 28 28]
  [28 28 28]]

 [[28 28 28]
  [28 28 28]
  [28 28 28]]]


In [46]:
# 넘파이 집계함수

# df.descripe 를 이용하여 sum, mean, std, max, min(기초통계량) 한번에 알 수 있음 ?!?

arry4 = np.arange(1,25).reshape(3,4,2)

print(arry4)
# axis=None 
print(arry4.sum())
print(np.sum(arry4))

# axis = 0 row를 고정하고 연산
print("axis = 0\n",arry4.sum(axis = 0))     #print(sum(arry4))

# axis = 1 column을 고정하고 연산
print("axis = 1\n",arry4.sum(axis=1)) #결과는 (3,2)

# axis = 2 depth를 고정하고 연산
print("axis = 2\n",arry4.sum(axis=2)) #결과는 (3,4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
300
300
axis = 0
 [[27 30]
 [33 36]
 [39 42]
 [45 48]]
axis = 1
 [[16 20]
 [48 52]
 [80 84]]
axis = 2
 [[ 3  7 11 15]
 [19 23 27 31]
 [35 39 43 47]]


In [52]:
 # 넘파이 정렬

 arry5 = np.array([2,3,6,8,1,4,9])
 # np.sort()를 활용할 경우 정렬된 결과값을 반환하지만 기존의 데이터는 그대로
 sorted_arry5 = np.sort(arry5)
 print(sorted_arry5)
 print(arry5,"\n")

# ndarray.sort()를 활용할 경우 원본 데이터를 수정함
# arry5.sort()
print(arry5)

 # np.argsort()는 오름차순으로 정렬된 배열의 인덱스 값만 반환함
 sort_index = np.argsort(arry5)
 print(sort_index)

[1 2 3 4 6 8 9]
[2 3 6 8 1 4 9] 

[2 3 6 8 1 4 9]
[4 0 1 5 2 3 6]
